export type IconName =
	| "check"
	| "checkCircleOutline"
	| "chevronDoubleLeft"
	| "chevronDoubleRight"
	| "chevronDown"
	| "chevronRight"
	| "chevronLeft"
	| "chevronUp"
	| "close"
	| "delete"
	| "edit"
	| "github"
	| "google"
	| "heartFilled"
	| "heartOutlined"
	| "menu"
	| "minusCircleOutline";
